### ISSUE TITLE
Control RNG

### ISSUE THREAD

**Issue by rcalxrc08** [iitis/DatagenCopulaBased.jl#1]
Hi, very nice library.
I am noticing that there is no way to actually pass to the copula generator a prescribed random number generator (like in randn, rand etc).
It would be very nice to have such a functionality.

**Comment by kdomino** [comment]
done in version 1.1

**Comment by rcalxrc08** [comment]
Actually it is not solved, I can't use custom rng inside your library.
Look at rand as example, you have various implementation of it, one of those has an argument that is the random number generator that you want to use.
Instead your library always calls the global random number generator, in case of multiple process/threads this can be really bad.

**Comment by kdomino** [comment]
Are you thinking about something like that?

simulate_copula(t::Int, copula::TypeOfCopula; custom_rn_generator::MersenneTwister = Random.GLOBAL_RNG)

**Comment by kdomino** [comment]
Or rather I will do

simulate_copula(t::Int, copula::TypeOfCopula; rng::AbstractRNG = Random.GLOBAL_RNG)

**Comment by rcalxrc08** [comment]
second one is better since shorter :).
Once implemented you can leverage on others rng like the ones in [RandomNumbers.jl](https://www.google.cz/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjAvaaQ-oDpAhXSUxUIHaZzCdkQFjAAegQICBAC&url=https%3A%2F%2Fgithub.com%2Fsunoru%2FRandomNumbers.jl&usg=AOvVaw3JT5VelRv81004xnO7D1ni)

**Comment by kdomino** [comment]
Ok, it will be done, however I need some time

**Comment by rcalxrc08** [comment]
No worries, if I will have time I will try to open a pr.

**Comment by kdomino** [comment]
Done in version 1.2
